# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.3
        with:
          # List of .bicep files to build, delimited by a space. eg) file1 file2 file3 ...
          files: deploy/azure.deploy.bicep deploy/azure.sub.deploy.bicep
          # Version of the bicep CLI. It can be the exact version (eg. `v0.3.255`), wildcard (eg. `v0.3.x`) or `latest`. If omitted, `latest` is set as default.
          version: latest # optional, default is latest
      - name: Add & Commit
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@2bdc0a61a03738a1d1bda24d566ad0dbe3083d87
        uses: EndBug/add-and-commit@v7.2.1
        with:
          # Arguments for the git add command
          add: deploy/azure.deploy.json deploy/azure.sub.deploy.json
          message: Built main ARM templates via GitHub Action CI
